version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.8.1
    - 1.9.1
  - dependency-name: rails
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: elasticsearch-transport
    versions:
    - 7.10.1
    - 7.11.2
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: puma
    versions:
    - 5.1.1
  - dependency-name: pghero
    versions:
    - 2.7.3
  - dependency-name: sanitize
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: intl-messageformat
    versions:
    - 9.4.2
    - 9.4.9
    - 9.5.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.21.5
    - 7.22.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: esquery
    versions:
    - 1.3.1
